=== StarExec/StarExec/batch-job-schema/batchJobSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="https://www.starexec.org/starexec/public/batchJobSchema.xsd" targetNamespace="https://www.starexec.org/starexec/public/batchJobSchema.xsd">
    
    <annotation>
    	<documentation>
    		This is the xml schema for creating starexec jobs. 
    	</documentation>
    </annotation>
    
    <element name="Jobs" type="tns:Jobs"></element>
    
    <complexType name="Jobs">
    	<sequence>
    		<element name="Job" type="tns:Job" minOccurs="1" 
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="Job">
    	<sequence>

	  <element name="JobAttributes" type="tns:JobAttributes"></element>

    		<element name="JobPair" type="tns:JobPair" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	
    	<!-- The job name must be unique to the space -->
    	<attribute name="name" type="tns:PrimitiveName" use="required"></attribute>
    	
    </complexType>
    
    <complexType name="JobAttributes">
      <all>
	<element name="description" type="tns:descriptionInfo" maxOccurs="1" minOccurs="0"></element>
    	<!-- You can find the id of a queue on the Cluster=>Status page -->
    	<element name="queue-id" type="tns:intInfo"></element>
    	
    	<!-- The default for start-paused is false -->
    	<element name="start-paused" type="tns:booleanInfo" maxOccurs="1" minOccurs="0"></element>
    	<element name="preproc-id" type="tns:intInfo" maxOccurs="1" minOccurs="0"></element>
    	<element name="postproc-id" type="tns:intInfo" maxOccurs="1" minOccurs="0"></element>
    	
    	<!-- Note: Timeouts are in seconds -->
    	<element name="cpu-timeout" type="tns:intInfo"></element>
    	<element name="wallclock-timeout" type="tns:intInfo"></element>
    	
    	<!-- Note: This is in Gigabytes -->
    	<element name="mem-limit" type="tns:doubleInfo"></element>
	
      </all>
      
    </complexType>

    <!-- job attributes type definitions -->
    <complexType name="intInfo">
      <attribute name="value" type="int" use="required"></attribute>
    </complexType>

    <complexType name="descriptionInfo">
      <attribute name="value" type="tns:Description" use="required"></attribute>
    </complexType>

    <complexType name="booleanInfo">
      <attribute name="value" type="boolean" use="required"></attribute>
    </complexType>

    <complexType name="doubleInfo">
      <attribute name="value" type="double" use="required"></attribute>
    </complexType>
    
    <!-- end job attributes type definitions -->

    
    <complexType name="JobPair">
    	<attribute name="bench-id" type="int" use="required"></attribute>
    	<attribute name="bench-name" type="tns:PrimitiveName" use="optional"></attribute>
    	
    	<!-- A configuration id uniquely identifies a solver, so no more is required -->
    	<attribute name="config-id" type="int" use="required"></attribute>
    	<attribute name="config-name" type="tns:PrimitiveName" use="optional"></attribute>
    	
    	<attribute name="solver-id" type="int" use="optional"></attribute>
    	<attribute name="solver-name" type="tns:PrimitiveName" use="optional"></attribute>
    	
    	<attribute name="job-space-id" type="int" use="optional"></attribute>
    	<attribute name="job-space-path" type="tns:Path" use="optional"></attribute>
    </complexType>
    
    <simpleType name="Description">
    	<restriction base="string">
    		<pattern value="[^&lt;&gt;&quot;&apos;)(&amp;&#37;&#43;&#45;]{0,1024}" />
    	</restriction>
    </simpleType>
    
    <simpleType name="PrimitiveName">
  		<restriction base="string">
    		<pattern value="[_\w\-\.\+\^=,!?:$%#@ ]{1,255}"/>
  		</restriction>
	</simpleType>
	
	<simpleType name="Path">
  		<restriction base="string">
    		<pattern value="[_/\w\-\.\+\^=,!?:$%#@ ]*"/>
  		</restriction>
	</simpleType>
    
</schema>

=== StarExec/StarExec/batch-job-schema/ExampleJob.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:Jobs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.starexec.org/starexec/public/batchJobSchema.xsd batchJobSchema.xsd" xmlns:tns="https://www.starexec.org/starexec/public/batchJobSchema.xsd">
<Job name="Example Job Name" cpu-timeout="10" wallclock-timeout="20" queue-id="1" mem-limit="1.0" start-paused="true" description="This example job runs solver config 1 with 6 benchmarks on all.q.">
<JobPair bench-id="1" config-id="1"></JobPair>
<JobPair bench-id="3" config-id="1"></JobPair>
<JobPair bench-id="4" config-id="1"></JobPair>
<JobPair bench-id="5" config-id="1"></JobPair>
<JobPair bench-id="8" config-id="1"></JobPair>
<JobPair bench-id="9" config-id="1"></JobPair>
</Job>
</tns:Jobs>

=== StarExec/StarExec/schemas/ExampleJob.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:Jobs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.starexec.org/starexec/public/batchJobSchema.xsd batchJobSchema.xsd" xmlns:tns="https://www.starexec.org/starexec/public/batchJobSchema.xsd">
<Job name="another test">
<JobAttributes>
<description value="just a test"/>
<queue-id value="1"/>
<start-paused value="true"/>
<cpu-timeout value="2"/>
<wallclock-timeout value="2"/>
<mem-limit value="2.0"/>
</JobAttributes>
<JobPair bench-id="11" bench-name="add4.smt2" config-id="3" config-name="default" job-space-id="1" job-space-path="cvc" solver-id="3" solver-name="CVC4-SMT-COMP-2010"/>
<JobPair bench-id="12" bench-name="add5.smt2" config-id="3" config-name="default" job-space-id="1" job-space-path="cvc" solver-id="3" solver-name="CVC4-SMT-COMP-2010"/>
</Job>
</tns:Jobs>
