=== StarExec/StarExec/batch-space-schema/batchSpaceSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="https://www.starexec.org/starexec/public/batchSpaceSchema.xsd" targetNamespace="https://www.starexec.org/starexec/public/batchSpaceSchema.xsd">
    
    <annotation>
    	<documentation>
    		This is the xml schema for a starexec space hierarchy. 
    	</documentation>
    </annotation>
 
    <element name="Spaces" type="tns:Spaces" ></element>
    
     <complexType name="Spaces">
    	<sequence>
    		<element name="Space" type="tns:Space" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
	</complexType>
    
    <complexType name="Space">
    	<sequence>
    		<element name="Benchmark" type="tns:Benchmark" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="Solver" type="tns:Solver" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="Space" type="tns:Space" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	 <attribute name="id" type="int" use="optional"></attribute>
    	 <attribute name="sticky-leaders" type="boolean" use="optional"></attribute>
    	 <attribute name="inherit-users" type="boolean" use="optional"></attribute>
    	 <attribute name="locked" type="boolean" use="optional"></attribute>
	 <attribute name="description" type="tns:Description" use="optional"></attribute>
    	 <attribute name="add-benchmark-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="add-job-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="add-solver-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="add-space-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="add-user-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="rem-benchmark-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="rem-job-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="rem-solver-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="rem-space-perm" type="boolean" use="optional"></attribute>
    	 <attribute name="rem-user-perm" type="boolean" use="optional"></attribute>
    	 
    	 <!-- This should not be null and must have at least 1 character -->
    	 <attribute name="name" type="tns:PrimitiveName"></attribute>	
    </complexType>

    <complexType name="Benchmark">
        <sequence>
  	  <element name="Attribute" type="tns:Attribute" minOccurs="0" maxOccurs="unbounded">
    	  </element>
        </sequence>
    	<attribute name="id" type="int"></attribute>
    	<attribute name="name" type="string" use="optional"></attribute>
    </complexType>
    
    <complexType name="Attribute">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>

    <complexType name="Solver">
    	<attribute name="id" type="int"></attribute>
    	<attribute name="name" type="string" use="optional"></attribute>
    </complexType>
    

    <simpleType name="Description">
      <restriction base="string">
	<pattern value="[^&lt;&gt;&quot;&apos;)(&amp;&#37;&#43;&#45;]{0,1024}" />
      </restriction>
    </simpleType>

    <simpleType name="PrimitiveName">
  		<restriction base="string">
    		<pattern value="[_\w\-\. \+\^=,!?:$%#@]{1,250}"/>
  		</restriction>
	</simpleType>

    
</schema>

=== StarExec/StarExec/batch-space-schema/ExampleSpace.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:Spaces xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://stardev.cs.uiowa.edu/starexec_jccervantes/public/batchSpaceSchema.xsd batchSpaceSchema.xsd" xmlns:tns="https://stardev.cs.uiowa.edu/starexec_jccervantes/public/batchSpaceSchema.xsd">
<Space id="11" name="cvc">
<SpaceAttributes>
<description value="the true test"/>
<sticky-leaders value="true"/>
<inherit-users value="true"/>
<locked value="true"/>

<add-benchmark-perm value="false"/>
<add-job-perm value="false"/>
<add-solver-perm value="false"/>
<add-space-perm value="false"/>
<add-user-perm value="false"/>
<rem-benchmark-perm value="false"/>
<rem-job-perm value="false"/>
<rem-solver-perm value="false"/>
<rem-space-perm value="false"/>
<rem-user-perm value="false"/>
</SpaceAttributes>
<Benchmark id="11" name="add4.smt2">
<Attribute name="status" value="unsat"/>
<Attribute name="set-logic" value="QF_AUFLIA"/>
<Attribute name="smt-lib-version" value="2.0"/>
<Attribute name="category" value="industrial"/>
</Benchmark>
<Benchmark id="12" name="add5.smt2">
<Attribute name="status" value="unsat"/>
<Attribute name="set-logic" value="QF_AUFLIA"/>
<Attribute name="smt-lib-version" value="2.0"/>
<Attribute name="category" value="industrial"/>
</Benchmark>
</Space>
</tns:Spaces>
